### PR TITLE
LRAC-12806 Remove batch feature flag

### PR DESCRIPTION
**Pull request by rachaelkoestartyo**

### CODE REVIEW

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:relevant

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by rachaelkoestartyo** [comment]
ci:test:sf

**Comment by ivicac** [comment]
Resent https://github.com/liferay-ac/liferay-portal/pull/548

**Comment by ivicac** [comment]
ci:close

**Pull request closed without merging**
